# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Friends of Pheasant Branch Conservancy
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://friendsofpheasantbranch.org" # the base hostname & protocol for your site
prose:
  rooturl: "_posts"
  ignore: [
    '_config.yml',
    'index.html',
    '/_includes',
    '/_layouts',
    '/_sass'
    ]
  metadata:
    _posts:
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "category"
        field:
          element: "multiselect"
          label: "Add Category"
          placeholder: "Select a Category"
          options:
            - name: "Restore"
              value: "restore"
            - name: "Education"
              value: "education"
            - name: "Watershed"
              value: "watershed"

# Build settings
markdown: kramdown
